homedir: ./
investing.com:
    Bond:
        AU: []
        DE: []
        FR: []
        JP: []
        KS: []
        UK: []
        US: []
    Currency:
        AUD: []
        EUR: []
        JPY: []
        USD: [US Dollar Index]
    Equity:
        Index:
            AU: []
            DE: []
            FR: []
            JP: []
            KS: []
            UK: []
            US: []            
        Indivisual:
            AU: []
            DE: []
            FR: []
            JP: []
            KS: []
            UK: []
            US: []

yfinance:
    Commodity:
        Gold: [GC=F]
        Silver: [SI=F]
        Oil: [CL=F]
        Gas: [NG=F]
        Corn: [C=F]
        Soybeans: [S=F]
        Wheat: [W=F]
    Equity:
        Index:
            AU: []
            DE: []
            FR: []
            JP: []
            KS: []
            UK: []
            US: []            
        Indivisual:
            AU: []
            DE: []
            FR: []
            JP: []
            KS: []
            UK: []
            US: []
    Forex:
        Forward:
            AUDUSD: []
            EURUSD: []
            GBPUSD: []
            USDJPY: []
        Spot:
            AUDUSD: [AUDUSD=X]
            EURUSD: [EURUSD=X]
            GBPUSD: [GBPUSD=X]
            USDJPY: [USDJPY=X]
